---

- set_fact:
    ROLLBACK_VERSION: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
  run_once: true
  delegate_to: 127.0.0.1

- name: "1、创建必要的目录"
  file:
    state: directory
    path: "{{ item.name }}"
    owner: hjmrunning
    group: hjmrunning
    #recurse: yes
  with_items:
    - { name: "/data/log" }
    - { name: "/opt/data" }
    - { name: "/opt/hjm/{{ aha_project_name }}/release/{{ aha_project_name }}.go{{ ROLLBACK_VERSION }}" }
  become: yes

- name: "2、推送run.sh"
  copy:
    src: "{{ ans_git_workspace }}/GO/run.sh.j2"
    dest: "/opt/hjm/{{ aha_project_name }}/run.sh"
    force: yes
    mode: 0750

- name: "3、判断{{ aha_project_name }}是否运行..."
  shell: "ps -ef | grep {{ aha_project_name }} | grep -v grep | wc -l"
  register: ans_project_processes

- name: "判断输出"
  debug: var=ans_project_processes

- name: "4、停止/opt/hjm/{{ aha_project_name }}"
  shell: "source /etc/profile;/bin/bash run.sh stop {{ aha_project_name }}"
  register: kill_project
  args:
    chdir: "/opt/hjm/{{ aha_project_name }}"
  ignore_errors: True
  when: ans_project_processes is defined

- name: "输出是否kill掉"
  debug: var=kill_project

- name: "休眠20s"
  shell: "sleep 20"

- name: "5、上传到/opt/hjm/{{ aha_project_name }}/release/{{ ROLLBACK_VERSION }}"
  copy:
    src: "{{ ans_jenkins_workspace }}/{{ ans_project_name }}/{{ aha_project_name }}"
    dest: "/opt/hjm/{{ aha_project_name }}/release/{{ aha_project_name }}.go{{ ROLLBACK_VERSION }}/"
    force: yes
    mode: 0755
  register: copy_go_done

- name: "6、创建软链"
  shell: "cd /opt/hjm/{{ aha_project_name }} && ln -snf release/{{ aha_project_name }}.go{{ ROLLBACK_VERSION }} current"

- name: "7、启动/opt/hjm/{{ aha_project_name }}"
  shell: "source /etc/profile  && ./run.sh start {{ aha_project_name }}"
  args:
    chdir: /opt/hjm/{{ aha_project_name }}
  when: copy_go_done is defined

- name: "8、sleep 50"
  shell: "sleep 20"

- name: "9、See index.jsp page"
  shell: "curl  {{ ans_go_test_url }}"
  register: jsp

- debug: var=jsp.stdout

- name: "10、清理历史包，保留{{ ans_keep_releases }}个"
  shell: ls -1dt /opt/hjm/{{ aha_project_name }}/release/* | tail -n +{{ ans_keep_releases | int + 1 }} | xargs rm -rf
  when: ans_keep_releases > 0
...
