# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "rules/*rules.yml"            #   rules目录和prometheus.yml是同一个目录
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.6.2.116:9090']
      labels:
        instance: prometheus     

  - job_name: 'centos-10.6.2.111'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.6.2.111:9100']
      labels:
        instance: node-10.6.2.111    ##### 这边的labels 到后面 grafana的时候可以做到正则匹配

  - job_name: 'centos-10.6.2.112'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.6.2.112:9100']
      labels:
        instance: node-10.6.2.112

  - job_name: 'centos-10.6.2.113'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.6.2.113:9100']
      labels:
        instance: node-10.6.2.113

  - job_name: 'centos-10.6.2.114'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.6.2.114:9100']
      labels:
        instance: node-10.6.2.114

  - job_name: 'centos-10.6.2.115'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.6.2.115:9100']
      labels:
        instance: node-10.6.2.115

  - job_name: pushgateway
    static_configs:
    - targets: ['10.6.2.116:9091']
      labels:
        instance: pushgateway  ########  这边这个定义没什么意义了 pushgateway 都是靠curl后面那些个参数自己设定的
    honor_labels: true

  - job_name: discover_server
    file_sd_configs:
      - files:
        - /usr/local/prometheus/discover/discover_server.json  ## 自动发现存储
        refresh_interval: 10s 

