---
- hosts: '{{ hosts_name }}'
  vars:
    department: php
    AppId: openapi
    env: '{{ env_name }}'
    ans_project_name: aha-api-server
    aha_project_name: aha-api-server
  roles:
    - php_role_template
...
